apiVersion: apps/v1
kind: Deployment
metadata:
  name: halfbaked-app
  namespace: superpower-halfbaked
spec:
  replicas: 2
  selector:
    matchLabels:
      app: halfbaked-app
  template:
    metadata:
      labels:
        app: halfbaked-app
    spec:
      containers:
      - name: halfbaked-app
        image: __AWS_ECR_URL__/__SERVICE__:__VERSION__
        ports:
        - containerPort: 3000
        env:
          - name: VITE_API_URL
            value: https://api-halfbaked.superpower-staging.com
          - name: NODE_ENV
            value: staging

---

apiVersion: v1
kind: Service
metadata:
  name: halfbaked-app
  namespace: superpower-halfbaked
  annotations:
    external-dns.alpha.kubernetes.io/hostname: halfbaked-app.superpower-staging.com
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <ARN_OF_YOUR_SSL_CERTIFICATE>
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  selector:
    app: halfbaked-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 3000
  type: LoadBalancer
